on: [pull_request]

jobs:
  changelog_comment_pr:
    runs-on: ubuntu-latest
    name: Comment on Changelog requires
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
          FILES_MODIFIED: ${{ steps.file_changes.outputs.files_modified }}
        run: echo "$STEPS_CONTEXT"

      - name: detect change scope
        uses: actions/github-script@0.8.0
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
          FILES_ADDED: ${{ steps.file_changes.outputs.files_added }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env)
            const diff_url = context.payload.pull_request.diff_url
            return {buildtool: true, coregem: true}

      - name: Comment on build tools change log
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Consider adding a changelog entry'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
