on: [pull_request]

jobs:
  changelog_comment_pr:
    runs-on: ubuntu-latest
    name: Comment on Changelog requires
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: detect change scope
        id: change_scope
        uses: actions/github-script@0.8.0
        env:
          FILES_ADDED: ${{ steps.file_changes.outputs.files_added }}
          FILES_MODIFIED: ${{ steps.file_changes.outputs.files_modified }}
          FILES_DELETED: ${{ steps.file_changes.outputs.files_deleted }}

        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env)
            console.log("----------------")
            console.log(JSON.parse(process.env.FILES_ADDED))
            const diff_url = context.payload.pull_request.diff_url
            return {buildtool: true, coregem: true}

      - name: Output the scope
        run: echo "The time was ${{ steps.change_scope.outputs.result }}"
