on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Analyze and validate changes
      id: hello
      uses: alextwoods/changelog-action@master
      with:
        who-to-greet: 'Rubyist4'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
